# Generated by Django 2.2 on 2021-01-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingdojo_wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
